name: Code Quality

on:
  workflow_call:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
          

      - name: Run ESLint
        run: npx eslint .