name: deploy  to server 

on:
  push:
    branches:
      dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo: "hay login successfull"
            mkdir DevOps
      