name: deploy  to server 

on:
  push:
    branches:
      dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7

        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.KEY }}

          source: "docker-compose.yml"
          target: "/home/ec2-user/DevOps"


      - name: ssh to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo: "hay login successfull"
            mkdir -p DevOps
      