name: deploy  

on:
  workflow_call:
    secrets:
      key:
        required: true
      EC2_SSH_HOST:
        required: true
      EC2_SSH_USERNAME:
        required: true

      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          EC2_SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
          EC2_SSH_USERNAME: ${{ secrets.EC2_SSH_USERNAME }}
          KEY: ${{ secrets.KEY }}

          source: "docker-compose.yml,database/*"
          target: "/home/ubuntu/DevOps"    


      - name: ssh to server
        uses: appleboy/ssh-action@v1
        with:
          EC2_SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
          EC2_SSH_USERNAME: ${{ secrets.EC2_SSH_USERNAME }}
          KEY: ${{ secrets.KEY }}
          script: |
            mkdir -p DevOps
            cd ~/DevOps
            cat > .env << EOF
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=7d
            NODE_ENV=production
            EOF

            docker compose pull
            docker compose up -d --force-recreate

            
      