name: deploy to server

on:
  push:
    branches: [dev]
    

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  backend:
    uses: ./.github/workflows/backend.yaml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deployment:
    needs: [frontend,backend]
    uses: ./.github/workflows/deploy.yaml
    secrets:
      EC2_SSH_HOST: ${{ secrets.EC2_SSH_HOST }}
      EC2_SSH_USERNAME: ${{ secrets.EC2_SSH_USERNAME }}
      EY: ${{ secrets.KEY }}


      