name: frontend 

on:
  push:
    branches: [ dev ]
    paths:
      - frontend/**
      - .github/workflows/frontend.yaml

      
jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: dependency install 
        run: npm install
        working-directory: ./frontend

      - name: Run linters
        run: npm run lint
        working-directory: ./frontend

      - name: run tests
        run: npm test
        working-directory: ./frontend

      - name: security check
        run: npm audit --audit-level=critical || true
        working-directory: ./frontend

      

           


