name: frontend 

on:
  push:
    branches: [ dev ]
    paths:
      - frontend/**
      - .github/workflows/frontend.yaml

      
jobs:
  frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: dependency install 
        run: npm install
        working-directory: ./frontend

      - name: Run linters
        run: npm run lint
        working-directory: ./frontend

      - name: run tests
        run: npm test
        working-directory: ./frontend

      - name: dependency check
        run: npm audit --audit-level=critical || true
        working-directory: ./frontend

      - name: build 
        run: npm run build
        working-directory: ./frontend
      
      - name: Build Docker Image
        run: docker build -t frontend:latest .
        working-directory: ./frontend

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:latest
          format: table
          exit-code: 1
          severity: "CRITICAL"   



      

           


